export const CATEGORIES = [
  "Acne Prone/Oily Skin",
  "Acne Solutions",
  "Anti Aging",
  "Facial Care Hyperpigmentation",
  "Body Care Hyperpigmentation",
  "Body Care",
  "Face Care",
  "Moisturizers",
  "Dry Skin",
  "Our Best Sellers",
  "Sensitive Skin",
  "Sun Defence",
  "Skin Brighteners",
  "Psoriasis/Dry Flaky Skin",
]

export const PRODUCT_TYPES = [
  "Face Cleanser",
  "Face Serum",
  "Face Moisturizer",
  "Face Mask",
  "Sheet Mask",
  "Eye Cream",
  "Toner",
  "Exfoliator",
  "SPF",
  "Face Oil",
  "Mist",
  "Body Lotion",
  "Body Cream",
  "Treatment",
]

export const SKIN_CONCERNS = [
  "Acne",
  "Aging",
  "Oiliness",
  "Dryness",
  "Sensitivity",
  "Dehydration",
  "Dark Spots",
  "Hyperpigmentation",
  "Dullness",
  "Fine Lines",
  "Large Pores",
  "Congestion",
  "Redness",
  "Uneven Texture",
  "Psoriasis",
  "Brightening",
]
